---
roles: {}
collections:
- name: ansible.netcommon
  version: 2.1.0
- name: community.crypto
  version: 1.1.0
- name: community.general
  version: 1.1.0
- name: junipernetworks.junos
  version: 2.0.1
- name: cisco.ios
  version: 0.0.2
- name: cisco.iosxr
  version: 1.0.2
- name: netbox.netbox
  version: 1.0.2
- name: napalm.napalm
  version: 0.9.13
